### ISSUE TITLE
How to render JSON object?

### ISSUE THREAD

**Issue by ZeissS** [flabbergast-config/flabbergast#53]
I am bit unsure if this is a bug or I just didn't get Flabbergast yet -  lets see.

I want to generate a simple JSON output:

```
render_lib : From lib:render


t : render_lib.json.object {
	children : [
		render_lib.json.scalar {
			arg : "This is 'Sparta'"
			json_name : "name"
			
		}
	]
}

value : t.json_value
```

Expected output:

```
{"name": "This is 'Sparta'"}
```

Currently I get this output:

```
$ flabbergast test.o_o
/usr/share/flabbergast/lib/utils.o_0:93:46-93:57: There are 343 type-derived flows in the generated code. This will be slow to compile.
Attribute “arg” must be overridden.
  ├ /usr/share/flabbergast/lib/render.o_0: 90:2-91:16: attribute requiring override: arg
  ├─┬ test.o_o: 4:4-12:1: instantiated
  │ ├─┬ /usr/share/flabbergast/lib/render.o_0: 78:10-87:2: amend template
  │ │ ├ /usr/share/flabbergast/lib/render.o_0: 88:1-98:2: attribute: scalar
  │ │ ├ /usr/share/flabbergast/lib/render.o_0: 48:7-99:1: literal frame
  │ │ ├ /usr/share/flabbergast/lib/render.o_0: 47:0-99:1: attribute: json
  │ │ └ /usr/share/flabbergast/lib/render.o_0: 1:1-350:1: file contents
  │ ├ /usr/share/flabbergast/lib/render.o_0: 78:10-87:2: extend existing template
  │ ├ /usr/share/flabbergast/lib/render.o_0: 77:1-87:2: attribute: object
  │ ├ /usr/share/flabbergast/lib/render.o_0: 48:7-99:1: literal frame (previously mentioned)
  │ ┊
  ├ test.o_o: 4:4-12:1: template instantiation
  ├ test.o_o: 4:0-12:1: attribute: t
  └ test.o_o: 1:1-14:20: file contents
{"f0000000001":"my json scalar value"}
```

I get some kind of JSON output, but 2 warnings and the fieldname in the JSON object does not match my `json_name` attribute. Reading the `render.o_O` code doesn't help much either. I believe I am doing the right thing here. 

Can you give me a hint?

**Comment by apmasell** [comment]
There was a bug. It got fixed in 9a679e8f089f5287ef68f5f94b17189b3912d047, but didn't get included in the last release. You can download that one file and then run `update-flabbergast`.

Sorry.

**Comment by ZeissS** [comment]
Cool. I will try.

Could I request an example in the examples folder though? :) I checked there first, because the docs at http://docs.flabbergast.org/doc-render.xml didn't really help me initially either.

**Comment by apmasell** [comment]
Sure. Do you have some sample JSON you want to produce? That would be easier for me than just inventing some non-sense.

Also, I'm trying to make sure everything has documentation, but most of it has no feedback from users. I'm happy to change documentation if you can tell me what your needs are.

**Comment by ZeissS** [comment]
I guess something really dumb is totally fine as a starter thing, just for people getting the grasp of how to combine things. It doesn't need to be a real-world example IMHO.

Regarding the json issue: I edited my `render.o_O` and called `update-flabbergast`, but the fieldname is still wrong:

```
$ flabbergast test.o_o
/usr/share/flabbergast/lib/utils.o_0:93:46-93:57: There are 343 type-derived flows in the generated code. This will be slow to compile.
{"f0000000001":"my json scalar value"}
```

**Comment by ZeissS** [comment]
ah, nevermind. I don't have the json_name stuff either. I will replace the whole file.

**Comment by apmasell** [comment]
Okay. Sorry, the rendering library hasn't gotten thorough testing. The JSON stuff just got a shake down due to the JSON importer I just added. You should not that it can generate technically invalid JSON as NaN and infinity are not allowed.

**Comment by ZeissS** [comment]
Thats not a problem. Still having fun so far thinking how our ugly internal code for generating systemd unit files (which are actually just list of tuples (section, name, value)) to flabbergast. Looks like I not ran into an endless loop or sthg. I guess thats a new issue :)

Regarding the docs: How about just extending my minimal object example above with a second field for a list and putting some numbers in there? I guess that should get people started quickly.

**Comment by ZeissS** [comment]
Here is a simple example script (?) building scalars, an object and a list:

```
render_lib : From lib:render

example_obj : render_lib.json.object {
	children : [
		render_lib.json.list {
			json_name : "valid_range"
			children : [
				render_lib.json.scalar {
					arg : 1
					
				},
				render_lib.json.scalar {
					arg : 900000000000000
					
				}
			]
		},
		render_lib.json.scalar {
			json_name : "name"
			arg : "json example code"
		},
		render_lib.json.scalar {
			json_name : "is_example"
			arg : True
		}
	]
}

value : example_obj.json_value
```

Output:
```
$ flabbergast json.o_O
/usr/share/flabbergast/lib/utils.o_0:93:46-93:57: There are 343 type-derived flows in the generated code. This will be slow to compile.
{"valid_range":[1, 900000000000000], "name":"json example code", "is_example":true}
```

**Comment by apmasell** [comment]
Thanks!

**Comment by ZeissS** [comment]
Closed via c2015d84e7bb4459eefd3290d13849cd65185434
